export const products = [
    { id: 1, name: "Wheat-flour", price: 140, img: "https://greengrocery.com.bd/wp-content/uploads/2025/02/wheat-flour.jpg" },
    { id: 2, name: "Premium Dates Combo (খেজুর কম্বো)", price: 990, img: "https://greengrocery.com.bd/wp-content/uploads/2025/02/dates-4-1.jpg" },
    { id: 3, name: "Premium Medjool Dates (প্রিমিয়াম মেডজুল খেজুর)", price: 890, img: "https://greengrocery.com.bd/wp-content/uploads/2025/02/dates-3.jpg" },
    { id: 4, name: "Premium Ajwa Dates (প্রিমিয়াম আজওয়া খেজুর)", price: 850, img: "https://greengrocery.com.bd/wp-content/uploads/2025/02/dates-1.jpg" },
    { id: 5, name: "Premium Mariami Dates (প্রিমিয়াম মরিয়ম খেজুর)", price: 750, img: "https://greengrocery.com.bd/wp-content/uploads/2025/02/dates-2-1.jpg" },
    { id: 6, name: "Mutton Bone in (Khashi) ± 50 gm", price: 1100, img: "https://greengrocery.com.bd/wp-content/uploads/2024/12/Mutton-Bone-in-Khashi-%C2%B1-50-gm.jpeg" },
    { id: 7, name: "Broiler Whole Chicken (Skin On ± 50 gm)", price: 350, img: "https://greengrocery.com.bd/wp-content/uploads/2024/12/Chicken_broiler_skin.jpeg" },
    { id: 8, name: "Premium Gawa Ghee - 1KG", price: 1390, img: "https://greengrocery.com.bd/wp-content/uploads/2024/11/ghee-1kg.jpg" },
    { id: 9, name: "Beef Regular Cut (mixed)", price: 750, img: "https://greengrocery.com.bd/wp-content/uploads/2024/05/beef.jpg" },
    { id: 10, name: "Mustard Oil 10 Liter", price: 2880, img: "https://greengrocery.com.bd/wp-content/uploads/2024/05/mustard-oil-offer.jpg" },
    { id: 11, name: "Raw Cinnamon ( প্রিমিয়াম দারুচিনি)", price: 190, img: "https://greengrocery.com.bd/wp-content/uploads/2023/12/cinnamon-2.jpg" },
    { id: 12, name: "Roasted Cumin Powder 250 gm", price: 320, img: "https://greengrocery.com.bd/wp-content/uploads/2023/12/cumin-250-1.jpg" },
    { id: 13, name: "Nut Combo-(প্রিমিয়াম বাদাম কম্বো)", price: 1199, img: "https://greengrocery.com.bd/wp-content/uploads/2023/09/nutty-1.jpg" },
    { id: 14, name: "Pistachio Nuts (পেস্তা বাদাম)", price: 2050, img: "https://greengrocery.com.bd/wp-content/uploads/2023/08/pistachio.jpg" },
    { id: 15, name: "Almond Nuts (কাঠ বাদাম)", price: 750, img: "https://greengrocery.com.bd/wp-content/uploads/2023/08/almond.jpg" },
    { id: 16, name: "Cashew Nuts (কাজু বাদাম)", price: 1090, img: "https://greengrocery.com.bd/wp-content/uploads/2023/08/cashewnut.jpg" },
    { id: 17, name: "Roasted Cashew Nuts (ভাজা কাজু বাদাম)", price: 1120, img: "https://greengrocery.com.bd/wp-content/uploads/2023/08/roasted-cashew.jpg" },
    { id: 18, name: "Pumpkin Seed (কুমড়া বীজ)", price: 520, img: "https://greengrocery.com.bd/wp-content/uploads/2023/08/pumpkin.jpg" },
    { id: 19, name: "Chia Seeds (চিয়া সিড)", price: 475, img: "https://greengrocery.com.bd/wp-content/uploads/2023/08/chia-seed-1.jpg" },
    { id: 20, name: "Gram Flour (বেসন)", price: 110, img: "https://greengrocery.com.bd/wp-content/uploads/2023/08/besan-1.jpg" },
    { id: 21, name: "Homemade Naga Pickle", price: 340, img: "https://greengrocery.com.bd/wp-content/uploads/2023/06/WhatsApp-Image-2023-06-20-at-3.49.48-PM.jpeg" },
    { id: 22, name: "Homemade Garlic Pickle", price: 300, img: "https://greengrocery.com.bd/wp-content/uploads/2023/06/garlic-4.jpg" },
    { id: 23, name: "Garbanzo (ছোলা)", price: 150, img: "https://greengrocery.com.bd/wp-content/uploads/2022/12/Garbanjo.jpeg" },
    { id: 24, name: "Soybean (ডাবলি বুট)", price: 110, img: "https://greengrocery.com.bd/wp-content/uploads/2022/12/Soybean.jpeg" },
    { id: 25, name: "Raw Masala Box - (শাহী র'মশলা কম্বো)", price: 999, img: "https://greengrocery.com.bd/wp-content/uploads/2022/10/raw-masala-1.jpg" },
    { id: 26, name: "Premium Najirshail Rice (নাজিরশাইল চাল)", price: 510, img: "https://greengrocery.com.bd/wp-content/uploads/2022/10/Najirshail-5kg.jpeg" },
    { id: 27, name: "Premium Gawa Ghee (Small)", price: 320, img: "https://greengrocery.com.bd/wp-content/uploads/2022/09/Gawa-ghee-180g-2.jpg" },
    { id: 28, name: "Premium Gawa Ghee", price: 590, img: "https://greengrocery.com.bd/wp-content/uploads/2022/09/Gawa-ghee-180g-1.jpg" },
    { id: 29, name: "Mustard Flower Honey (সরিষা ফুলের মধু)", price: 250, img: "https://greengrocery.com.bd/wp-content/uploads/2022/09/Mustard-oil-honey-5.jpg" },
    { id: 30, name: "Black Seed Flower Honey (কালোজিরা ফুলের মধু)", price: 465, img: "https://greengrocery.com.bd/wp-content/uploads/2022/09/Black-seed-honey-3.jpg" },
    { id: 31, name: "", price: 0, img: "" },
    { id: 32, name: "", price: 0, img: "" },
    { id: 33, name: "", price: 0, img: "" },
    { id: 34, name: "", price: 0, img: "" },
    { id: 35, name: "", price: 0, img: "" },
    { id: 36, name: "", price: 0, img: "" },
    { id: 37, name: "", price: 0, img: "" },
    { id: 38, name: "", price: 0, img: "" },
    { id: 39, name: "", price: 0, img: "" },
    { id: 40, name: "", price: 0, img: "" },
    { id: 41, name: "", price: 0, img: "" },
    { id: 42, name: "", price: 0, img: "" },
    { id: 43, name: "", price: 0, img: "" },
    { id: 44, name: "", price: 0, img: "" },
    { id: 45, name: "", price: 0, img: "" },
    { id: 46, name: "", price: 0, img: "" },
    { id: 47, name: "", price: 0, img: "" },
    { id: 48, name: "", price: 0, img: "" },
    { id: 49, name: "", price: 0, img: "" },
    { id: 50, name: "", price: 0, img: "" },
    { id: 51, name: "", price: 0, img: "" },
    { id: 52, name: "", price: 0, img: "" },
    { id: 53, name: "", price: 0, img: "" },
    { id: 54, name: "", price: 0, img: "" },
    { id: 55, name: "", price: 0, img: "" },
    { id: 56, name: "", price: 0, img: "" },
    { id: 57, name: "", price: 0, img: "" },
    { id: 58, name: "", price: 0, img: "" }
  ];
  